### ISSUE TITLE
Security headset issue.

### ISSUE THREAD

**Issue by Anatidaephobic** [The-ArchAngels/Baystation12#1]
#### Brief description of the issue
Joined as Detective (Private investigator). Security headset's size was 'bulky'.
#### What you expected to happen
For the headset to be 'tiny', or at least 'small'.
#### What actually happened
It was 'bulky'.
#### Steps to reproduce
Join as security (Maybe Detective? Possibly Private investigator.). Examine headset.
#### Additional info:
 - **Server Revision**: *Found using the "Show Server Revision" verb under the OOC tab.*
unknown
 - **Game ID**: *This is a random string that is generated for each round, displayed when you login/relog to the server.
If you know the id for the round the reported issue occurred, please list it here.*
bIC-aoSy
 - *Anything else you may wish to add.* Nah.

**Comment by DJ-Chad97** [comment]
Issue will be fixed shortly

**Comment by DJ-Chad97** [comment]
Fixed [Should be]
